server:
  port: 8080

spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  # 静态资源 路径
  mvc:
    static-path-pattern: /static/**
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/webra_blog?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 数据库时区配置(数据库使用date java使用timeTram的原因,时区差8小时)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${upload.image.path}
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # session 超时时间
  session:
    timeout: 21600
  application:
    name: blog


# mybatis 配置
mybatis:
  type-aliases-package: top.webra.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper:
#  helper-dialect: mysql

# 图片存放路径
upload:
  image:
    path: E:\Code\webra-blog\imgs

#  # 热启动
#  devtools:
#    restart:
#      enabled: false #设置开启热部署
#      additional-paths: src/main/java #重启目录














